name: Synchronize openresty/openresty:1.19.3.1-3-alpine
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ main ]

jobs:
  hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push
        run: |
          bash ./sync.sh openresty/openresty 1.19.3.1-3-alpine
  aliyun-guangzhou:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: registry.cn-guangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_UAERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: Push
        run: |
          bash ./sync.sh openresty/openresty 1.19.3.1-3-alpine registry.cn-guangzhou.aliyuncs.com/tomhjx/mirrorspro
  aliyun-hongkong:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hongkong.aliyuncs.com
          username: ${{ secrets.ALIYUN_UAERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: Push
        run: |
          bash ./sync.sh openresty/openresty 1.19.3.1-3-alpine registry.cn-hongkong.aliyuncs.com/tomhjx/mirrorspro
