name: Synchronize registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.2
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ main ]

jobs:
  hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push
        run: |
          bash ./sync.sh registry.k8s.io/kube-state-metrics/kube-state-metrics v2.8.2
  aliyun-guangzhou:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: registry.cn-guangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_UAERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: Push
        run: |
          bash ./sync.sh registry.k8s.io/kube-state-metrics/kube-state-metrics v2.8.2 registry.cn-guangzhou.aliyuncs.com/tomhjx/mirrorspro

